{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm2pgsql-wrapper.name" . -}}
{{- $tracingUrl := include "osm2pgsql-wrapper.tracingUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-command-options-configmap
data:
  {{- with .Values.s3 }}
  S3_ENDPOINT: {{ printf "%s://%s:%v/" .protocol .host .port | quote }}
  S3_BUCKET_NAME: {{ .bucketName | quote }}
  S3_ACL: {{ .acl | quote }}
  PROJECT_ID: {{ .projectId | quote }}
  {{- end }}
  {{- with .Values.cli }}
  {{- if eq .command "append" }}
  CONFIG: {{ printf "%s/%s" .append.config.mountPath .append.config.fileName | quote }}
  {{- if .append.limit.enabled }}
  LIMIT: {{ .append.limit.value | quote }}
  {{- end }}
  REPLICATION_URL: {{ .append.replicationUrl | quote }}
  {{- end }}
  {{- if eq .command "create" }}
  DUMP_SOURCE_TYPE: {{ .create.dumpSourceType | quote }}
  DUMP_SOURCE: {{ .create.dumpSource | quote }}
  S3_LUA_SCRIPT_KEY: {{ .create.s3LuaScriptKey | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
