{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm2pgsql-wrapper.name" . -}}
{{- $tracingUrl := include "osm2pgsql-wrapper.tracingUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-command-options-configmap
data:
  {{- with .Values.s3 }}
  S3_ENDPOINT: {{ printf "%s://%s:%v/" .protocol .host .port | quote }}
  S3_BUCKET_NAME: {{ .bucketName | quote }}
  S3_KEY_ID: {{ .keyId | quote }}
  S3_ACL: {{ .acl | quote }}
  {{- end }}
  COMMAND: {{ .Values.cli.command | quote }}
  {{- if eq .Values.cli.command "append" }}
  CONFIG: {{ printf "%s/%s" .Values.cli.append.config.mountPath .Values.cli.append.config.fileName | quote }}
  REPLICATION_URL: {{ .Values.cli.append.replicationUrl | quote }}
  {{- end }}
  {{- if eq .Values.cli.command "create" }}
  DUMP_SOURCE_TYPE: {{ .Values.cli.create.dumpSourceType | quote }}
  DUMP_SOURCE: {{ .Values.cli.create.dumpSource | quote }}
  S3_SCRIPT_KEY: {{ .Values.cli.create.s3ScriptKey | quote }}
  {{- end }}
{{- end -}}
