{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm2pgsql-wrapper.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-command-options-configmap
data:
  {{- with .Values.s3 }}
  S3_ENDPOINT: {{ printf "%s://%s:%v/" .protocol .host .port | quote }}
  S3_BUCKET_NAME: {{ .bucketName | quote }}
  S3_PROJECT_ID: {{ .projectId | quote }}
  {{- end }}
  {{- if eq .Values.cli.command "append" }}
  S3_ACL: {{ .Values.s3.acl | quote }}
  CONFIG: {{ printf "%s/%s" .Values.cli.append.config.mountPath .Values.cli.append.config.fileName | quote }}
  REPLICATION_URL: {{ .Values.cli.append.replicationUrl | quote }}
  UPLOAD_TARGETS: {{ .Values.cli.append.uploadTargets | quote }}
  NAME: {{ .Values.cli.append.queue.name | quote }}
  {{- if .Values.deployment.enabled }}
  FOREVER: 'true'
  WAIT_TIME_SECONDS: {{ .Values.deployment.waitTimeSeconds | quote }}
  {{- end }}
  MIN_ZOOM: {{ .Values.cli.append.queue.minZoom | quote }}
  MAX_ZOOM: {{ .Values.cli.append.queue.maxZoom | quote }}
  {{- end }}
  {{- if eq .Values.cli.command "create" }}
  DUMP_SOURCE_TYPE: {{ .Values.cli.create.dumpSourceType | quote }}
  DUMP_SOURCE: {{ .Values.cli.create.dumpSource | quote }}
  S3_LUA_SCRIPT_KEY: {{ .Values.cli.create.s3LuaScriptKey | quote }}
  {{- end }}
{{- end -}}
