{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm2pgsql-wrapper.name" . -}}
{{- $tracingUrl := include "osm2pgsql-wrapper.tracingUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  {{- with .Values.postgres }}
  PGHOST: {{ .host }}
  PGPORT: {{ .port | default 5432 | quote }}
  PGDATABASE: {{ .database }}
  POSTGRES_ENABLE_SSL_AUTH: {{ .sslAuth.enabled | quote }}
  {{- if .sslAuth.enabled }}
  POSTGRES_CERTS_MOUNT_PATH: {{ .sslAuth.mountPath | quote }}
  {{- end }}
  {{- end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote | default "false" }}
  TELEMETRY_TRACING_ENABLED: {{ .Values.env.tracing.enabled | quote }}
  {{- if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  TELEMETRY_TRACING_RATIO: {{ .Values.env.tracing.ratio | quote }}
  {{- end }}
  HTTP_CLIENT_TIMEOUT: {{ .Values.env.httpClient.timeout | quote }}
  OSM2PGSQL_SLIM: {{ .Values.env.osm2pgsql.slim | quote}}
  OSM2PGSQL_CACHE: {{ .Values.env.osm2pgsql.cache | quote }}
  OSM2PGSQL_PROCESSES: {{ .Values.env.osm2pgsql.processes | quote }}
  OSM2PGSQL_OUTPUT: {{ .Values.env.osm2pgsql.output | quote }}
  OSM2PGSQL_GENERATE_EXPIRE_OUTPUT: {{ .Values.env.osm2pgsql.generateExpireOutput | quote }}
  OSM2PGSQL_LOG_LEVEL: {{ .Values.env.osm2pgsql.log.Level | quote }}
  OSM2PGSQL_LOG_PROGRESS: {{ .Values.env.osm2pgsql.log.progress | quote }}
  OSM2PGSQL_LOG_SQL: {{ .Values.env.osm2pgsql.log.sql | quote }}
  OSM2PGSQL_LOG_SQL_DATA: {{ .Values.env.osm2pgsql.log.sqlData | quote }}
  OSM2PGSQL_SCHEMA: {{ .Values.env.osm2pgsql.schema | quote }}
  OSM2PGSQL_MIDDLE_SCHEMA: {{ .Values.env.osm2pgsql.middleSchema | quote }}
  OSMIUM_VERBOSE: {{ .Values.env.osmium.verbose | quote }}
  OSMIUM_PROGRESS: {{ .Values.env.osmium.progress | quote }}
  {{- with .Values.pgboss }}
  PGBOSS_HOST: {{ .host | quote }}
  PGBOSS_PORT: {{ .port | default 5432 | quote }}
  PGBOSS_DATABASE: {{ .database | quote }}
  PGBOSS_SCHEMA: {{ .schema | quote }}
  PGBOSS_ENABLE_SSL_AUTH: {{ .sslAuth.enabled | quote }}
  {{- if .sslAuth.enabled }}
  PGBOSS_ENABLE_SSL_AUTH: "true"
  PGBOSS_CERTS_MOUNT_PATH: {{ .sslAuth.mountPath | quote }}
  PGBOSS_CERT_PATH: /tmp/certs-pgboss/{{ .sslAuth.certFileName }}
  PGBOSS_KEY_PATH: /tmp/certs-pgboss/{{ .sslAuth.keyFileName }}
  PGBOSS_CA_PATH: /tmp/certs-pgboss/{{ .sslAuth.caFileName }}
  {{- else }}
  PGBOSS_ENABLE_SSL_AUTH: "false"
  {{- end }}
  {{- end }}
{{- end -}}
