{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osm2pgsql-wrapper.name" . -}}
{{- $tracingUrl := include "osm2pgsql-wrapper.tracingUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  {{- with .Values.postgres }}
  PGHOST: {{ .host }}
  PGPORT: {{ .port | default 5432 | quote }}
  PGDATABASE: {{ .database }}
  POSTGRES_ENABLE_SSL_AUTH: {{ .sslAuth.enabled | quote }}
  {{- if .sslAuth.enabled }}
  POSTGRES_CERTS_MOUNT_PATH: {{ .sslAuth.mountPath | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.s3 }}
  S3_ENDPOINT: {{ printf "%s://%s:%v/" .protocol .host .port | quote }}
  S3_BUCKET_NAME: {{ .bucketName | quote }}
  S3_KEY_ID: {{ .keyId | quote }}
  S3_ACL: {{ .acl | quote | default "public-read" }}
  {{- end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote | default "false" }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: "true"
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{- else }}
  TELEMETRY_TRACING_ENABLED: "false"
  {{- end }}
  HTTP_CLIENT_TIMEOUT: {{ .Values.env.httpClient.timeout | quote }}
  {{ if .Values.env.osm2pgsql.slim }}
  OSM2PGSQL_SLIM: "true"
  {{- else }}
  OSM2PGSQL_SLIM: "false"
  {{- end }}
  OSM2PGSQL_CACHE: {{ .Values.env.osm2pgsql.processes | quote }}
  OSM2PGSQL_PROCESSES: {{ .Values.env.osm2pgsql.processes | quote }}
  OSM2PGSQL_OUTPUT: {{ .Values.env.osm2pgsql.output | quote }}
  OSM2PGSQL_LOG_LEVEL: {{ .Values.env.osm2pgsql.logLevel | quote }}
  OSM2PGSQL_LOG_PROGRESS: {{ .Values.env.osm2pgsql.logProgress | quote }}
  {{ if .Values.env.osmium.verbose }}
  OSMIUM_VERBOSE: "true"
  {{- else }}
  OSMIUM_VERBOSE: "false"
  {{- end }}
  {{ if .Values.env.osmium.progress }}
  OSMIUM_PROGRESS: "true"
  {{- else }}
  OSMIUM_PROGRESS: "false"
  {{- end }}
{{- end -}}
