{{- $chartName := include "osm2pgsql-wrapper.name" . -}}
{{- if and (.Values.enabled) (eq .Values.cli.command "append") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-schema-configmap
data:
  {{ .Values.cli.append.config.fileName }}: {{ tpl (.Files.Get "config/append-config.json") . | quote }}
{{- end }}
