{{- if and (.Values.enabled) (eq .Values.cli.command "append") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-schema-configmap" (include "osm2pgsql-wrapper.fullname" .) }}
data:
  {{ .Values.cli.append.config.fileName }}: {{ printf "%s" .Values.cli.append.config.path | .Files.Get | quote }}
{{- end }}
