{
 "title": "osm2pgsql-wrapper - instance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "project name",
    "query": {
     "query": "label_values(osm2pgsql_wrapper_append_duration_seconds_count{},project)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(metatile_queue_populator_populate_requests_handled{project=\"$projectName\"},instance)"
    }
   },
   {
    "name": "script",
    "label": "script name",
    "query": {
     "query": "label_values(osm2pgsql_wrapper_append_duration_seconds_count{},script)"
    }
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(osm2pgsql_wrapper_expire_tiles_attempted_uploads_counter{},target)"
    }
   },
   { "name": "interval", "query": "1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "total appends since restart",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (osm2pgsql_wrapper_appends_count{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "attempted expire-tiles uploads per target",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (target, status) (osm2pgsql_wrapper_expire_tiles_attempted_uploads_counter{instance=\"$instance\"})",
     "legendFormat": "{{retrycount}}"
    }
   ]
  },
  {
   "title": "generated expire-tiles since restart",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "osm2pgsql_wrapper_tiles_counter{kind='generated_expire_list', instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "generated bbox item requests since restart",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "osm2pgsql_wrapper_tiles_counter{kind='requested_bbox_items', instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests in queue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "osm2pgsql_wrapper_requests_queue_current_count{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "appends in $interval window",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(osm2pgsql_wrapper_appends_count{instance=\"$instance\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "expire-tiles uploads in $interval window",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (target, status) (increase(osm2pgsql_wrapper_expire_tiles_attempted_uploads_counter{instance=\"$instance\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": " $projectName  project appends duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "repeat": "projectName",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(osm2pgsql_wrapper_append_duration_seconds_bucket{instance=\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(osm2pgsql_wrapper_append_duration_seconds_bucket{instance=\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "rate(osm2pgsql_wrapper_append_duration_seconds_sum{instance=\"$instance\"}[$interval]) / rate(osm2pgsql_wrapper_append_duration_seconds_sum{instance=\"$instance\"}[$interval])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "expire-tiles upload to $target duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "repeat": "target",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(osm2pgsql_wrapper_expire_tiles_uploads_duration_seconds_bucket{instance=\"$instance\", target=\"$target\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(osm2pgsql_wrapper_expire_tiles_uploads_duration_seconds_bucket{instance=\"$instance\", target=\"$target\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "rate(osm2pgsql_wrapper_expire_tiles_uploads_duration_seconds_sum{instance=\"$instance\", target=\"$target\"}[$interval]) / rate(osm2pgsql_wrapper_expire_tiles_uploads_duration_seconds_sum{instance=\"$instance\", target=\"$target\"}[$interval])",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=\"$instance\"}[$interval]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=\"$instance\"}[$interval]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}