global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development

revisionHistoryLimit: 5 # Amount of revisions we keep
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: false

nameOverride: ""
fullnameOverride: ""

configManagement:
  offlineMode: false
  name: 'service-name'
  version: 'latest'
  serverUrl: 'http://localhost:8080/api'

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  path: /liveness

podAnnotations: {}

extraVolumes: []

extraVolumeMounts: []

extraEnvVars: []

command: []
args: []
# command: [ "/bin/sh", "-c", "--" ]
# args: [ "while true; do sleep infinity; done;" ]

sidecars: []

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: ''
  imagePullSecretName: ''

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: osm2pgsql-wrapper
  # If commented, appVersion will be taken. See: _helpers.tpl
  # tag: 'latest'
  pullPolicy: IfNotPresent

deployment:
  enabled: false
  waitTimeSeconds: 30

job:
  enabled: true
  apiVersion: 'batch/v1' # depends on openshift version batch/v1 or batch/v1beta1
  restartPolicy: OnFailure
  ttlSecondsAfterFinished: 60
  backoffLimit: 6

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
    ratio: 1
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  httpClient:
    timeout: 1000
  osm2pgsql:
    slim: true
    extraAttributes: false
    cache: 2500
    processes: 2
    output: flex
    generateExpireOutput: true
    schema: public
    middleSchema: public
    log:
      level: info
      progress: true
      sql: false
      sqlData: false
  osmium:
    verbose: false
    progress: false

postgres:
  host: localhost
  username: postgres
  password: postgres
  database: osm2pgsql
  # port: 5432
  sslAuth:
    enabled: false
    secretName: secret-name
    mountPath: '/tmp/certs-postgres'

pgboss:
  host: localhost
  username: postgres
  password: postgres
  database: job
  schema: pgboss
  port: 5432
  sslAuth:
    enabled: false
    secretName: secret-name
    mountPath: '/tmp/certs-pgboss'
    certFileName: postgresql.crt
    keyFileName: postgresql.key
    caFileName: root.crt

s3:
  accessKey: accessKey
  secretKey: secret
  protocol: http
  host: localhost
  port: 9000
  bucketName: osm2pgsql
  projectId: someId
  acl: private

cli:
  command: 'create' # create or append
  append:
    replicationUrl: 'https://planet.openstreetmap.org/replication/minute'
    config:
      mountPath: '/tmp/config'
      fileName: 'config.json'
      path: 'config/append-config.json'
    uploadTargets:
      enabled: false
      value: 's3,queue' # the upload targets separated with a comma with no space
    queue:
      name: queueName
      minZoom: 1
      maxZoom: 18
  create:
    dumpSourceType: remote-url # local-file, remote-url or dump-server
    dumpSource: 'https://remote-url.com'
    s3LuaScriptKey: script.lua
    # stateOverride:

mdr:
  enabled: false
  client:
    url: 'https://mdr.com'
    timeout: 10000

arstotzka:
  enabled: false
  serviceId: id
  networkCM: arstotzka-network-configmap
  mediator:
    timeout: 10000
    retryStrategy:
      enabled: fasle
      # retries: 3
      # shouldResetTimeout: false
      # isExponential: false
      # delay: 100
