global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: my-registry-url.io

image:
  repository: osm2pgsql-wrapper
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 'v1.0.0'
  pullPolicy: Always

cron:
  schedule: '* */1 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  restartPolicy: OnFailure
  apiVersion: 'batch/v1' # depends on openshift version batch/v1 or batch/v1beta1

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

env:
  logLevel: info
  logPrettyPrintEnabled: false
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  httpClient:
    timeout: 1000
  osm2pgsql:
    slim: true
    cache: 2500
    processes: 2
    output: flex
    logLevel: info
    logProgress: true
  osmium:
    verbose: false
    progress: false

postgres:
  host: localhost
  username: postgres
  password: postgres
  database: osm2pgsql
  # port: 5432
  sslAuth:
    enabled: false
    secretName: secret-name
    mountPath: '/tmp/certs-postgres'

s3:
  accessKey: accessKey
  secretKey: secret
  protocol: http
  host: localhost
  port: 9000
  bucketName: osm2pgsql
  keyId: someId
  acl: private

cli:
  command: 'create' # create or append
  append:
    replicationUrl: 'https://planet.openstreetmap.org/replication/minute'
    config:
      mountPath: '/tmp'
      fileName: 'config.json'
  create:
    dumpSourceType: remote-url # local-file, remote-url or dump-server
    dumpSource: 'https://remote-url.com'
    s3ScriptKey: script.lua

configSchema: |-
  [
    {
      "id": "ways",
      "script": "sub-simple-ways.lua",
      "zoomLevel": {
        "min": 1,
        "max": 3
      }
    },
    {
      "id": "pois",
      "script": "sub-simple-pois.lua",
      "zoomLevel": {
        "min": 4,
        "max": 5
      }
    }
  ]
