name: pull_request

on: [pull_request, workflow_dispatch]

jobs:
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/init-npm
        with:
          node-version: ${{ matrix.node }}

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          prettier: true
          eslint_extensions: ts

  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/init-npm
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: npm run test

      - uses: actions/upload-artifact@v4
        with:
          name: Test Reporters ${{ matrix.node }}
          path: ./reports/**


  build_image:
    name: Build Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: build Docker image
        run: docker build -t test-build:latest --build-arg NODE_VERSION .
        env:
          NODE_VERSION: ${{ matrix.node }}
